# Generated by Django 5.0.2 on 2024-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog_remove_product_view_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Человекопонятный URL'),
        ),
    ]
