# Generated by Django 5.0.2 on 2024-03-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_blog_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at', 'is_active', 'view_counter'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
