# Generated by Django 5.0.2 on 2024-03-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_blog_options_remove_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at', 'is_published', 'view_counter'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='is_active',
            new_name='is_published',
        ),
    ]
