# Generated by Django 5.0.2 on 2024-03-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, help_text='Укажите номер версии', verbose_name='Номер версии')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название версии')),
                ('working_ver', models.BooleanField(default=False, help_text='Укажите признак текущей версии', verbose_name='Признак версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('product', 'number', 'name', 'working_ver'),
            },
        ),
    ]
