# Generated by Django 5.0.2 on 2024-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_version_options_alter_version_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='working_ver',
            field=models.BooleanField(blank=True, help_text='Укажите признак текущей версии', null=True, verbose_name='Признак версии'),
        ),
    ]
